# Question 1

#### 1. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [2]:
import numpy as np

In [3]:
np.random.randint(0,11,5)

array([7, 7, 4, 6, 7])

# Question 2
#### Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values​​except the first and last.

In [13]:
A=np.arange(15,56)
A[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

# Question 3
#### Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements.

In [17]:
x=np.random.randn(10000)
print('Average of the array element:')
x.mean()

Average of the array element:


-0.006294022677893941

In [18]:
print('Variance of the array element:')
x.var()

Variance of the array element:


0.9842725949802763

In [19]:
print('standard deviation of the array element:')
x.std()

standard deviation of the array element:


0.9921051330278845

# Question 4
#### Write a NumPy program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array

In [22]:
z=np.array([[1,2,3],[4,5,6]])
print('Original array')
print(z)
print('Cumulative sum of elements along a given axis:')
x=np.cumsum(z)
print(x)
print('\nSum over rows for each oof the 3 columns:')
x=np.cumsum(z,axis=0)
print(x)
print ('\nSum over columns for each of the 2 rows:')
x=np.cumsum(z,axis=1)
print(x)

Original array
[[1 2 3]
 [4 5 6]]
Cumulative sum of elements along a given axis:
[ 1  3  6 10 15 21]

Sum over rows for each oof the 3 columns:
[[1 2 3]
 [5 7 9]]

Sum over columns for each of the 2 rows:
[[ 1  3  6]
 [ 4  9 15]]


# Question 5
#### Write a NumPy program to compute the multiplication of two given matrixes. Sample Matrix: 

[[1, 0], [0, 1]] 

[[1, 2], [3, 4]]

In [23]:
a=[[1,0],[0,1]]
b=[[1,2],[3,4]]
print('Original Matrix:')
print(a)
print(b)
d=np.dot(a,b)
print('multiplication result') 
print(d)

Original Matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
multiplication result
[[1 2]
 [3 4]]
